version: "3.8"
services:
  db:
    container_name: pg_whois_db
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=MIET2023
      - POSTGRES_USER=postgres
  bot:
    restart: always
    container_name: tg_whois_bot
    build: .
    depends_on: 
      - db